SKILLS = {
    "Python": ["python", "py"],
    "JavaScript": ["javascript", "js"],
    "TypeScript": ["typescript", "ts"],
    "Java": ["java"],
    "C++": ["c++"],
    "C#": ["c#", "c sharp"],
    "Go": ["golang", "go"],
    "Ruby": ["ruby"],
    "PHP": ["php"],
    "Rust": ["rust"],
    "SQL": ["sql"],
    "PostgreSQL": ["postgresql", "postgres"],
    "MySQL": ["mysql"],
    "MongoDB": ["mongodb", "mongo"],
    "Redis": ["redis"],
    "React": ["react", "react.js", "reactjs"],
    "React Native": ["react native", "react-native"],
    "Vue": ["vue", "vue.js", "vuejs"],
    "Angular": ["angular"],
    "Node.js": ["node.js", "nodejs", "node"],
    "Express": ["express", "express.js"],
    "Flask": ["flask"],
    "Django": ["django"],
    "FastAPI": ["fastapi"],
    "Spring": ["spring", "spring boot"],
    "HTML": ["html", "html5"],
    "CSS": ["css", "css3"],
    "Tailwind": ["tailwind", "tailwind css"],
    "Docker": ["docker"],
    "Kubernetes": ["kubernetes", "k8s"],
    "AWS": ["aws", "amazon web services"],
    "Azure": ["azure"],
    "GCP": ["gcp", "google cloud"],
    "Git": ["git"],
    "Linux": ["linux"],
    "REST": ["rest", "rest api", "restful"],
    "GraphQL": ["graphql"],
    "CI/CD": ["ci/cd", "cicd"],
    "pytest": ["pytest"],
    "Machine Learning": ["machine learning", "ml"],
}